export const experienceData = [
  {
    id: 1,
    company: 'APWin',
    jobtitle: 'Frontend Developer',
    startYear: '2023',
    endYear: '2024',
    techStack: ['HTML', 'Sass', 'Javascript', 'Bulma', 'Vue.JS', 'Laravel'],
  },
  {
    id: 2,
    company: 'Oasis Center Arena (Part Time)',
    jobtitle: 'Frontend Developer',
    startYear: '2023',
    endYear: '2024',
    techStack: ['Next.js', 'Tailwind', 'Prisma', 'Typescript'],
  },
  {
    id: 3,
    company: 'Worklifebeyond',
    jobtitle: 'Lead Frontend Developer',
    startYear: '2021',
    endYear: '2023',
    techStack: [
      'React.JS',
      'Typescript',
      'Material UI',
      'Tailwind',
      'Graphql',
      'Redux',
    ],
  },
  {
    id: 4,
    company: 'Worklifebeyond',
    jobtitle: 'Frontend Developer',
    startYear: '2019',
    endYear: '2021',
    techStack: [
      'React.JS',
      'Typescript',
      'Material UI',
      'Tailwind',
      'Graphql',
      'Redux',
    ],
  },
  {
    id: 5,
    company: 'Talenta x Sleekr',
    jobtitle: 'Frontend Developer',
    startYear: '2018',
    endYear: '2018',
    techStack: ['HTML', 'Sass', 'Javascript', 'Laravel'],
  },
]
